:sectlinks:
:toc:
:source-highlighter: highlightjs

= Angular 1/Angular 4 Hybrid App and Migration Guide
Andrew Azores <aazores@redhat.com>

Lessons Learned in Migrating an AngularJS App To AngularJS/Angular Hybrid

Assumptions: Using Webpack, ui-router, karma/mocha/sinon/should/istanbul/eslint

The goal of this guide is to aid in migrating an existing AngularJS project to
Angular and TypeScript, when also using Webpack and some additional test
frameworks and utilities.

This guide is a supplement to the official Angular upgrade/migration document:

https://angular.io/guide/upgrade#upgrading-from-angularjs

Read and follow along with the official guide. When you come across a
configuration that doesn't make sense, or hit a build issue, come back to this
document to find guidance on how to properly configure the tooling.

The official guide assumes you are using the TypeScript compiler on its own,
not with a build tool like Webpack, and also assumes that you are using Jasmine
test runner, and includes no guidance on setting up Istanbul code coverage
tooling either. There is a separate official Angular guide to using Webpack,
but it also doesn't talk about hybrid apps or code coverage.  It also glosses
over any kind of pre-bootstrap application logic, and since it uses only very
simplistic example code for both AngularJS and Angular, doesn't cover some
pitfalls that can occur depending on the existing AngularJS project setup.
This guide aims only to help with these specific hurdles.

First, we will look at the project structure. If this structure does not match
your project then you can either reorganize your project, or more simply,
modify some of the configuration files to match your structure. The particular
files to modify are `karma.conf.js`, `webpack.config.js`, and once it's added,
`tsconfig.json`.

We will then proceed to add TypeScript dependencies to the project and set it
up as an Angular hybrid app, but leave Angular "empty". In the next section we
will talk about "upgrading" existing AngularJS service code so that it is
available in Angular.

Then, once AngularJS services are ready to be shared with Angular components,
we will walk through how to migrate an AngularJS component to Angular and
TypeScript. Eventually, all AngularJS components will be migrated, and the app
can be reconfigured into a pure Angular app (this is not covered in this
document).

Finally, we will conclude with unit test modifications so that the test suite
can handle side-by-side AngularJS and Angular/TypeScript sources and tests.
You will even be able to migrate a component's sources to TypeScript while
leaving its tests in JavaScript, which can help ensure that the language port
is done without behavioural side effects. An addendum follows describing how to
configure code coverage reporting using Istanbul.

include::project_structure.adoc[]

include::adding_typescript.adoc[]

include::upgrading_services.adoc[]

include::migrating_components.adoc[]

include::testing.adoc[]
