== Bootstrapping and Upgrading AngularJS services for use in Angular

App startup order:

Angular bootstrap -> AngularJS bootstrap -> AngularJS module configuration

The official upgrade document talks about this
https://angular.io/guide/upgrade#bootstrapping-hybrid-applications[here],
but isn't so explicit about pitfalls that you may run across, depending on how
your project is broken down into modules and how you register those modules.

It's important to ensure that AngularJS module code is not actually executed
until after everything has been initialized and both frameworks have been
bootstrapped. In our case, the convention was for services, controllers, etc.
to live in their own miniature AngularJS modules, and for those modules to be
registered simply by the file being imported by some other file. Since all of
this happens statically before bootstrap time (kind of - we also use oclazyload,
but this works under the same model if you imagine the oclazyload loading
process as a module subtree bootstrapping), everything gets initialized and
registered before bootstrap. But this model no longer works when both frameworks
need to be bootstrapped, because you end up with difficult to resolve async
dependencies cropping up depending on which files are imported when.

This is also an issue if you use Webpack's require.context in order to do
build-time dynamic imports. In this case, you must ensure that any source files
which are imported via `require()` only export JavaScript modules, functions, etc., but
do *not* immediately declare any new Angular modules (using
`angular.module("foo", [])` - note the second, array parameter). If the file
does need to declare a new Angular module then this logic should be moved into
an exported function, and that function imported and then called elsewhere in
application logic explicitly after AngularJS bootstrap has occurred.

The solution used in Thermostat.next() Web-Client is to put all of this
AngularJS module setup work into exported functions and to call these functions
in an init function in our ang-app.module.js, as well as to avoid executing the
setup code multiple times. For example, here is a diff from several files
relating to our auth interceptor and services module:

[source,javascript]
----
--- a/src/app/ang-app.module.js
+++ b/src/app/ang-app.module.js
@@ -40,7 +40,6 @@
 import 'angularjs-datatables/dist/plugins/select/angular-datatables.select.min.js';
 
 import {default as authModule, config as authModSetup} from 'components/auth/auth.module.js';
-import authInterceptorFactory from './auth-interceptor.factory.js';
 
 require.ensure([], () => {
   require('angular-patternfly/node_modules/datatables.net-dt/css/jquery.dataTables.css');
@@ -55,6 +54,8 @@
 
 /* istanbul ignore next */
 function initializeApplication () {
  // services.module.js exports one of these module init functions, so here,
  // temporally after bootstrap has been performed, we require() that file and
  // invoke the init function, which will declare and register our shared
  // services module in AngularJS
+  require('shared/services/services.module.js').init();
+  let authInterceptorFactory = require('./auth-interceptor.factory.js').default;
   return angular
     .module(angApp, [
       'ui.router',
----

[source,javascript]
----
--- a/src/app/shared/services/services.module.js
+++ b/src/app/shared/services/services.module.js
@@ -35,5 +35,10 @@
   ])
   .name;
 
-let req = require.context('./', true, /\.service\.js/);
-req.keys().map(req);
// this is the shared services module init function that we just imported and
// invoked in ang-app.module.js. It uses a Webpack require.context() for a
// build-time dynamic discovery of all adjacent *.service.js files, which
// individually implement some shared service and register it upon the shared
// services module.
+export function init () {
+  let req = require.context('./', true, /\.service\.js/);
+  req.keys().map(key => {
+    let mod = req(key);
+    mod.init();
+  });
+}
----

This Angular module sets up our AngularJS service providers for DI under Angular.

[source,typescript]
----
--- a/src/app/shared/services/services.module.ts
+++ b/src/app/shared/services/services.module.ts
@@ -27,9 +27,29 @@
 
 import { NgModule } from '@angular/core';
 
+import {
+  commandChannelServiceProvider,
+  extractClassServiceProvider,
+  localStorageServiceProvider,
+  metricToBigIntServiceProvider,
+  multichartServiceProvider,
+  sanitizeServiceProvider,
+  scaleBytesServiceProvider,
+  webSocketFactoryProvider
+} from './ajs-upgraded-providers';
+
 @NgModule({
   imports: [],
   declarations: [],
-  providers: []
+  providers: [
+    commandChannelServiceProvider,
+    extractClassServiceProvider,
+    localStorageServiceProvider,
+    metricToBigIntServiceProvider,
+    multichartServiceProvider,
+    sanitizeServiceProvider,
+    scaleBytesServiceProvider,
+    webSocketFactoryProvider
+  ]
 })
 export class ServicesModule {}
----

[source,javascript]
----
--- a/src/app/shared/services/websocket-factory.service.js
+++ b/src/app/shared/services/websocket-factory.service.js
@@ -28,7 +28,7 @@
 import servicesModule from './services.module.js';
 
 /* istanbul ignore next */
// the class is exported so that it can be used as an injection token by the
// upgraded service provider seen below.
-class WebSocketFactory {
+export class WebSocketFactory {
   createSocket (connectUrl) {
     if ('WebSocket' in window) {
       return new WebSocket(connectUrl);
@@ -40,6 +40,8 @@
   }
 }
 
// here is another example of the init function convention, this time at the
// level of an individual shared service. This file does not declare a new
// AngularJS module, it only registers the WebSocketFactory class as a provider
// for "webSocketFactory". We do not want to run this code every time an
// external file imports websocket-factory.service.js, which will happen
// whenever another module has a dependency on the WebSocketFactory class and
// must import it for use as an Angular injection token.
-angular
-  .module(servicesModule)
-  .service('webSocketFactory', WebSocketFactory);
+export function init () {
+  angular
+    .module(servicesModule)
+    .service('webSocketFactory', WebSocketFactory);
+}
----

WARNING: Here we have a different approach from what the official Angular
migration guide suggests. This approach works well for a stopgap short term
solution to making services available in both frameworks, but it comes with
some important caveats. The advantage of this approach is that it allows for
the services and filters to be made available to both frameworks very quickly
with relatively little code written. The disadvantage is that AngularJS and
Angular will each retain their own runtime instance of each service - this
means there will be a small amount of additional memory used, but it also
causes difficulties for services that maintain internal state in memory. For
stateful services the best bet is to use the `downgradeInjectable` technique
laid out in the official guide.

This file defines Angular providers that import class definitions from shared
services implementation files and uses those definitions as both the injection
token and the implementation for a service. Here we are also injecting the
$injector service to each when it is instantiated by the Angular DI framework.
You can change the "$injector" dependency to suit each service, but there may
be difficulties with this approach as you incrementally migrate pieces from
AngularJS to Angular where dependencies are not injectable in one framework
when they are available in the other. To avoid this, you can use the $injector
service directly, which will be available in both frameworks.

This approach allows the service to remain implemented in JavaScript and
registered by AngularJS, as well as registered with Angular. This results in
the service class being injectable and usable by both AngularJS and Angular
code.

This `upgraded-providers` approach example also shows all services being
provided with the `$injector` service (via DI), rather than their exact
specific DI dependencies. In a real scenario, `$injector` should be replaced
by the list of actual dependencies for each service. However, in some cases,
the `$injector` does need to be directly used - specifically, if the service
has dependencies on AngularJS-only services (`$q` for example). You will be
able to grab the `$q` service via `$injector.get`, but `$q` won't be resolvable
by the Angular injector.

[source,typescript]
----
--- /dev/null
+++ b/src/app/shared/services/ajs-upgraded-providers.ts
@@ -0,0 +1,82 @@
+
+import { CommandChannelService } from './command-channel.service.js';
+export const commandChannelServiceProvider = {
+  provide: CommandChannelService,
+  useClass: CommandChannelService,
+  deps: ['$injector']
+};
+
+import { ExtractClassService } from './extract-class.service.js';
+export const extractClassServiceProvider = {
+  provide: ExtractClassService,
+  useClass: ExtractClassService,
+  deps: ['$injector']
+};
+
+import { LocalStorageService } from './local-storage.service.js';
+export const localStorageServiceProvider = {
+  provide: LocalStorageService,
+  useClass: LocalStorageService,
+  deps: ['$injector']
+};
+
+import { MetricToBigIntService } from './metric-to-big-int.service.js';
+export const metricToBigIntServiceProvider = {
+  provide: MetricToBigIntService,
+  useClass: MetricToBigIntService,
+  deps: ['$injector']
+};
+
+import { MultichartService } from './multichart.service.js';
+export const multichartServiceProvider = {
+  provide: MultichartService,
+  useClass: MultichartService,
+  deps: ['$injector']
+};
+
+import  { SanitizeService } from './sanitize.service.js';
+export const sanitizeServiceProvider = {
+  provide: SanitizeService,
+  useClass: SanitizeService,
+  deps: ['$injector']
+};
+
+import { ScaleBytesService } from './scale-bytes.service.js';
+export const scaleBytesServiceProvider = {
+  provide: ScaleBytesService,
+  useClass: ScaleBytesService,
+  deps: ['$injector']
+};
+
+import { WebSocketFactory } from './websocket-factory.service.js';
+export const webSocketFactoryProvider = {
+  provide: WebSocketFactory,
+  useClass: WebSocketFactory,
+  deps: ['$injector']
+};
----
